var lista = document.querySelector("ul");
var nome = lista.lastElementChild;
nome.innerHTML = "Taís";
var anchor = document.querySelector("li.list a");
anchor.style.color = 'red';
var botao = document.querySelector("button");
botao.style.backgroundColor = "yellow";
document.querySelector("h1").classList.toggle("huge");
document.querySelector("h1").classList.toggle("huge");
document.querySelector("a").setAttribute("href", "https://www.bing.com");
